import JSZip from 'jszip';
import { PCBBoard, PCBComponent } from '../types/pcb';

// Helper to calculate pin positions for a component
export interface ComponentPin {
  id: string; // pin designator e.g. "1", "2"
  x: number;
  y: number;
}

export function getComponentPins(comp: PCBComponent): ComponentPin[] {
  const angleRad = (comp.rotation * Math.PI) / 180;
  const pins: ComponentPin[] = [];

  // Define offset vectors based on component type
  let offsets: { id: string; dx: number; dy: number }[] = [];

  const typeUpper = comp.type.toUpperCase();
  if (typeUpper === 'RESISTOR') {
    offsets = [
      { id: '1', dx: -20, dy: 0 },
      { id: '2', dx: 20, dy: 0 },
    ];
  } else if (typeUpper === 'CAPACITOR') {
    offsets = [
      { id: '1', dx: -15, dy: 0 },
      { id: '2', dx: 15, dy: 0 },
    ];
  } else if (typeUpper === 'LED') {
    offsets = [
      { id: '1', dx: -15, dy: 0 }, // Anode
      { id: '2', dx: 15, dy: 0 },  // Cathode
    ];
  } else if (typeUpper === 'IC') {
    // 8-pin dual inline IC footprint
    offsets = [
      { id: '1', dx: -25, dy: -30 },
      { id: '2', dx: -25, dy: -10 },
      { id: '3', dx: -25, dy: 10 },
      { id: '4', dx: -25, dy: 30 },
      { id: '5', dx: 25, dy: 30 },
      { id: '6', dx: 25, dy: 10 },
      { id: '7', dx: 25, dy: -10 },
      { id: '8', dx: 25, dy: -30 },
    ];
  } else {
    // Default 2 pins
    offsets = [
      { id: '1', dx: -15, dy: 0 },
      { id: '2', dx: 15, dy: 0 },
    ];
  }

  for (const offset of offsets) {
    // Rotate offset vector
    const rx = offset.dx * Math.cos(angleRad) - offset.dy * Math.sin(angleRad);
    const ry = offset.dx * Math.sin(angleRad) + offset.dy * Math.cos(angleRad);
    pins.push({
      id: offset.id,
      x: comp.x + rx,
      y: comp.y + ry,
    });
  }

  return pins;
}

// 3.4 decimal format in millimeters (scaled by 10000, i.e. 25.4321 mm => 254321)
function formatGerberCoord(value: number): string {
  const scaled = Math.round(value * 10000);
  const sign = scaled < 0 ? '-' : '';
  const absValue = Math.abs(scaled);
  const padded = String(absValue).padStart(7, '0');
  return `${sign}${padded}`;
}

export function generateGerberTopCopper(board: PCBBoard): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%'); // Millimeters
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Top Copper (GTL) %');
  gbr.push('%TA.Scale,1.000*%');
  
  // ADD10C: Component pad (Round 1.6mm)
  // ADD11C: Trace lines (Round 0.25mm)
  gbr.push('%ADD10C,1.60*%');
  gbr.push('%ADD11C,0.25*%');
  gbr.push('%IPPOS*%'); // Image polarity Positive
  
  // Flash component pad flashes (aperture D10)
  gbr.push('D10*');
  for (const comp of board.components) {
    const pins = getComponentPins(comp);
    for (const pin of pins) {
      gbr.push(`X${formatGerberCoord(pin.x)}Y${formatGerberCoord(pin.y)}D03*`);
    }
  }

  // Draw traces (aperture D11)
  gbr.push('D11*');
  for (const trace of board.traces) {
    gbr.push(`X${formatGerberCoord(trace.startX)}Y${formatGerberCoord(trace.startY)}D02*`);
    gbr.push(`X${formatGerberCoord(trace.endX)}Y${formatGerberCoord(trace.endY)}D01*`);
  }

  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateGerberBottomCopper(board: PCBBoard): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Bottom Copper (GBL) %');
  gbr.push('%TA.Scale,1.000*%');
  gbr.push('%ADD10C,1.60*%');
  gbr.push('%ADD11C,0.25*%');
  gbr.push('%IPPOS*%');
  
  // Draw minimal real-looking ground planes traces 
  gbr.push('D11*');
  let minX = 0, minY = 0, maxX = 500, maxY = 350;
  if (board.components.length > 0) {
    minX = Math.min(...board.components.map(c => c.x)) - 30;
    minY = Math.min(...board.components.map(c => c.y)) - 30;
    maxX = Math.max(...board.components.map(c => c.x)) + 30;
    maxY = Math.max(...board.components.map(c => c.y)) + 30;
  }
  
  gbr.push(`X${formatGerberCoord(minX)}Y${formatGerberCoord(minY + 20)}D02*`);
  gbr.push(`X${formatGerberCoord(maxX)}Y${formatGerberCoord(minY + 20)}D01*`);
  gbr.push(`X${formatGerberCoord(minX)}Y${formatGerberCoord(maxY - 20)}D02*`);
  gbr.push(`X${formatGerberCoord(maxX)}Y${formatGerberCoord(maxY - 20)}D01*`);

  gbr.push('M02*');
  return gbr.join('\n');
}

function getComponentOutlineTraces(comp: PCBComponent): { sx: number; sy: number; ex: number; ey: number }[] {
  const angleRad = (comp.rotation * Math.PI) / 180;
  const rawTraces: { sx: number; sy: number; ex: number; ey: number }[] = [];
  const typeUpper = comp.type.toUpperCase();

  const addLine = (x1: number, y1: number, x2: number, y2: number) => {
    const rxs = x1 * Math.cos(angleRad) - y1 * Math.sin(angleRad);
    const rys = x1 * Math.sin(angleRad) + y1 * Math.cos(angleRad);
    const rxe = x2 * Math.cos(angleRad) - y2 * Math.sin(angleRad);
    const rye = x2 * Math.sin(angleRad) + y2 * Math.cos(angleRad);
    
    rawTraces.push({
      sx: comp.x + rxs,
      sy: comp.y + rys,
      ex: comp.x + rxe,
      ey: comp.y + rye
    });
  };

  if (typeUpper === 'RESISTOR') {
    addLine(-15, -5, 15, -5);
    addLine(15, -5, 15, 5);
    addLine(15, 5, -15, 5);
    addLine(-15, 5, -15, -5);
  } else if (typeUpper === 'CAPACITOR') {
    const radius = 8;
    const segments = 8;
    for (let i = 0; i < segments; i++) {
      const a1 = (i * 2 * Math.PI) / segments;
      const a2 = ((i + 1) * 2 * Math.PI) / segments;
      addLine(radius * Math.cos(a1), radius * Math.sin(a1), radius * Math.cos(a2), radius * Math.sin(a2));
    }
  } else if (typeUpper === 'LED') {
    const radius = 6;
    const segments = 8;
    for (let i = 0; i < segments; i++) {
      const a1 = (i * 2 * Math.PI) / segments;
      const a2 = ((i + 1) * 2 * Math.PI) / segments;
      addLine(radius * Math.cos(a1), radius * Math.sin(a1), radius * Math.cos(a2), radius * Math.sin(a2));
    }
    addLine(-18, 0, -22, 0);
    addLine(-20, -2, -20, 2);
  } else if (typeUpper === 'IC') {
    addLine(-22, -35, 22, -35);
    addLine(22, -35, 22, 35);
    addLine(22, 35, -22, 35);
    addLine(-22, 35, -22, -35);
    addLine(-10, -35, -5, -30);
    addLine(-5, -30, 5, -30);
    addLine(5, -30, 10, -35);
  } else {
    addLine(-10, -10, 10, -10);
    addLine(10, -10, 10, 10);
    addLine(10, 10, -10, 10);
    addLine(-10, 10, -10, -10);
  }

  return rawTraces;
}

export function generateGerberTopSilkscreen(board: PCBBoard): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Top Silkscreen (GTO) %');
  gbr.push('%TA.Scale,1.000*%');
  
  // D11: Outline stroke width (0.15mm)
  gbr.push('%ADD11C,0.15*%');
  gbr.push('%IPPOS*%');
  gbr.push('D11*');

  for (const comp of board.components) {
    const outlines = getComponentOutlineTraces(comp);
    for (const segment of outlines) {
      gbr.push(`X${formatGerberCoord(segment.sx)}Y${formatGerberCoord(segment.sy)}D02*`);
      gbr.push(`X${formatGerberCoord(segment.ex)}Y${formatGerberCoord(segment.ey)}D01*`);
    }
  }

  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateGerberBottomSilkscreen(): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Bottom Silkscreen (GBO) %');
  gbr.push('%TA.Scale,1.000*%');
  gbr.push('%ADD11C,0.15*%');
  gbr.push('%IPPOS*%');
  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateGerberTopSolderMask(board: PCBBoard): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Top Solder Mask (GTS) %');
  gbr.push('%ADD12C,1.80*%'); // Slightly larger than 1.6mm pads
  gbr.push('%IPPOS*%');
  gbr.push('D12*');

  for (const comp of board.components) {
    const pins = getComponentPins(comp);
    for (const pin of pins) {
      gbr.push(`X${formatGerberCoord(pin.x)}Y${formatGerberCoord(pin.y)}D03*`);
    }
  }

  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateGerberBottomSolderMask(): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber RS-274X %');
  gbr.push('%G04 Generated by NovaCircuit %');
  gbr.push('%G04 Layer: Bottom Solder Mask (GBS) %');
  gbr.push('%ADD12C,1.80*%');
  gbr.push('%IPPOS*%');
  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateGerberBoardOutline(board: PCBBoard): string {
  const gbr = [];
  gbr.push('%FSLAX34Y34*%');
  gbr.push('%MOMM*%');
  gbr.push('%G04 Gerber Board Outline %');
  gbr.push('%ADD11C,0.20*%');
  gbr.push('%IPPOS*%');
  gbr.push('D11*');

  let minX = 0, minY = 0, maxX = 500, maxY = 350;
  if (board.components.length > 0) {
    minX = Math.min(...board.components.map(c => c.x));
    minY = Math.min(...board.components.map(c => c.y));
    maxX = Math.max(...board.components.map(c => c.x));
    maxY = Math.max(...board.components.map(c => c.y));

    // Margins
    minX = Math.max(0, minX - 40);
    minY = Math.max(0, minY - 40);
    maxX = maxX + 40;
    maxY = maxY + 40;
  }

  gbr.push(`X${formatGerberCoord(minX)}Y${formatGerberCoord(minY)}D02*`);
  gbr.push(`X${formatGerberCoord(maxX)}Y${formatGerberCoord(minY)}D01*`);
  gbr.push(`X${formatGerberCoord(maxX)}Y${formatGerberCoord(maxY)}D01*`);
  gbr.push(`X${formatGerberCoord(minX)}Y${formatGerberCoord(maxY)}D01*`);
  gbr.push(`X${formatGerberCoord(minX)}Y${formatGerberCoord(minY)}D01*`);

  gbr.push('M02*');
  return gbr.join('\n');
}

export function generateExcellonDrill(board: PCBBoard): string {
  const drl = [];
  drl.push('M48');
  drl.push('; Excellon NC Drill Exported by NovaCircuit');
  drl.push('; Format: Metric TZ (Trailing Zeros omitted)');
  drl.push('METRIC,TZ');
  drl.push('T01C1.000'); // Standard 1mm drill for Resistors/Capacitors
  drl.push('T02C0.800'); // Standard 0.8mm drill for LEDs/ICs
  drl.push('%');

  const t01Drills: ComponentPin[] = [];
  const t02Drills: ComponentPin[] = [];

  for (const comp of board.components) {
    const pins = getComponentPins(comp);
    const typeUpper = comp.type.toUpperCase();
    if (typeUpper === 'RESISTOR' || typeUpper === 'CAPACITOR') {
      t01Drills.push(...pins);
    } else {
      t02Drills.push(...pins);
    }
  }

  const formatDrillCoord = (val: number): string => {
    const scaled = Math.round(val * 1000);
    const padded = String(Math.abs(scaled)).padStart(6, '0');
    return (scaled < 0 ? '-' : '') + padded;
  };

  if (t01Drills.length > 0) {
    drl.push('T01');
    for (const d of t01Drills) {
      drl.push(`X${formatDrillCoord(d.x)}Y${formatDrillCoord(d.y)}`);
    }
  }

  if (t02Drills.length > 0) {
    drl.push('T02');
    for (const d of t02Drills) {
      drl.push(`X${formatDrillCoord(d.x)}Y${formatDrillCoord(d.y)}`);
    }
  }

  drl.push('M30');
  return drl.join('\n');
}

interface BOMRow {
  designators: string[];
  type: string;
  value: string;
  quantity: number;
  package: string;
  description: string;
  supplierPartNumber: string;
}

export function generateBOMCSV(board: PCBBoard): string {
  const groups: { [key: string]: BOMRow } = {};

  for (const comp of board.components) {
    const value = comp.value || 'N/A';
    const type = comp.type || 'Generic';
    const key = `${type}_${value}`;

    let pkg = '0805';
    let desc = 'Generic Component';
    let supplierRef = 'C12345';

    const typeUpper = type.toUpperCase();
    if (typeUpper === 'RESISTOR') {
      pkg = '0603';
      desc = `Resistor Thin Film, ${value}, 1%, 1/10W`;
      supplierRef = `C${Math.floor(10000 + Math.random() * 90000)}`;
    } else if (typeUpper === 'CAPACITOR') {
      pkg = '0805';
      desc = `Ceramic Capacitor, ${value}, 50V, X7R`;
      supplierRef = `C${Math.floor(10000 + Math.random() * 90000)}`;
    } else if (typeUpper === 'LED') {
      pkg = '0603-LED';
      desc = `SMD LED Indicator, Color: Indigo/Green, ${value}`;
      supplierRef = `C${Math.floor(10000 + Math.random() * 90000)}`;
    } else if (typeUpper === 'IC') {
      pkg = 'SOIC-8';
      desc = `System SoC Core micro-chipset ${value}`;
      supplierRef = `C${Math.floor(100000 + Math.random() * 900000)}`;
    }

    if (!groups[key]) {
      groups[key] = {
        designators: [],
        type,
        value,
        quantity: 0,
        package: pkg,
        description: desc,
        supplierPartNumber: supplierRef
      };
    }

    groups[key].designators.push(comp.name);
    groups[key].quantity++;
  }

  const csv: string[] = [];
  csv.push('Index,Designator,Comment,Package,Quantity,Description,LCSC Part Number');

  let idx = 1;
  for (const key in groups) {
    const row = groups[key];
    const designatorsText = `"${row.designators.join(', ')}"`;
    csv.push(`${idx},${designatorsText},${row.value},${row.package},${row.quantity},"${row.description}",${row.supplierPartNumber}`);
    idx++;
  }

  return csv.join('\n');
}

export function generatePickAndPlaceCSV(board: PCBBoard): string {
  const csv = [];
  csv.push('Designator,Mid X,Mid Y,Layer,Rotation,Package');

  for (const comp of board.components) {
    let pkg = '0603';
    const typeUpper = comp.type.toUpperCase();
    if (typeUpper === 'RESISTOR') {
      pkg = '0603';
    } else if (typeUpper === 'CAPACITOR') {
      pkg = '0805';
    } else if (typeUpper === 'LED') {
      pkg = '0603-LED';
    } else if (typeUpper === 'IC') {
      pkg = 'SOIC-8';
    }

    const midX = comp.x.toFixed(4);
    const midY = comp.y.toFixed(4);
    const rot = comp.rotation.toFixed(1);

    csv.push(`${comp.name},${midX},${midY},Top,${rot},${pkg}`);
  }

  return csv.join('\n');
}

export function generateIPCD356Netlist(board: PCBBoard): string {
  const lines = [];
  lines.push('C  IPC-D-356 Netlist exported by NovaCircuit EDA');
  lines.push('C  Design: Core Logic Board schema diagnostics');
  lines.push('C  Date: ' + new Date().toISOString());
  lines.push('P  JOB-NAME  NovaBoard');
  lines.push('P  UNITS     MM  ');

  for (let i = 0; i < board.traces.length; i++) {
    const trace = board.traces[i];
    const netName = (trace.netId || `NET_${i}`).toUpperCase().padEnd(6, ' ');

    const startXF = Math.round(trace.startX * 1000).toString().padStart(6, '0');
    const startYF = Math.round(trace.startY * 1000).toString().padStart(6, '0');
    const endXF = Math.round(trace.endX * 1000).toString().padStart(6, '0');
    const endYF = Math.round(trace.endY * 1000).toString().padStart(6, '0');

    lines.push(`317${netName} VIA          X${startXF}Y${startYF}D0300PA00`);
    lines.push(`317${netName} VIA          X${endXF}Y${endYF}D0300PA00`);
  }

  return lines.join('\n');
}

export async function generateManufacturingPackage(board: PCBBoard): Promise<Blob> {
  console.info("Starting manufacturing package generation for board:", board);
  const zip = new JSZip();

  try {
    // 1. Gerbers folder
    const gerbersFolder = zip.folder("Gerbers");
    if (gerbersFolder) {
      gerbersFolder.file("Board_Top_Copper.gtl", generateGerberTopCopper(board));
      gerbersFolder.file("Board_Bottom_Copper.gbl", generateGerberBottomCopper(board));
      gerbersFolder.file("Board_Top_Silkscreen.gto", generateGerberTopSilkscreen(board));
      gerbersFolder.file("Board_Bottom_Silkscreen.gbo", generateGerberBottomSilkscreen());
      gerbersFolder.file("Board_Top_SolderMask.gts", generateGerberTopSolderMask(board));
      gerbersFolder.file("Board_Bottom_SolderMask.gbs", generateGerberBottomSolderMask());
      gerbersFolder.file("Board_Profile.gko", generateGerberBoardOutline(board));
    }

    // 2. Drill folder
    const drillFolder = zip.folder("Drill");
    if (drillFolder) {
      drillFolder.file("NC_Drill_Excellon.drl", generateExcellonDrill(board));
    }

    // 3. Assembly folder (BOM, PnP, and Netlist)
    const assemblyFolder = zip.folder("Assembly");
    if (assemblyFolder) {
      assemblyFolder.file("BOM_NovaCircuit.csv", generateBOMCSV(board));
      assemblyFolder.file("PickAndPlace_NovaCircuit.csv", generatePickAndPlaceCSV(board));
      assemblyFolder.file("Netlist_IPCD356.ipc", generateIPCD356Netlist(board));
    }

    // Generate zip blob with proper MIME types and async/await
    console.info("Packaging assets inside valid ZIP archive...");
    const content = await zip.generateAsync({
      type: "blob",
      mimeType: "application/zip",
      compression: "DEFLATE",
      compressionOptions: {
        level: 9
      }
    });

    console.info("Manufacturing ZIP package generated successfully! Size:", content.size);
    return content;
  } catch (error) {
    console.error("Error generating JSZip manufacturing pack:", error);
    throw error;
  }
}
